/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import {HTMLStencilElement, JSXBase} from '@stencil/core/internal';
import {
  Patient,
} from './components/patient-list/patient';

export namespace Components {
  interface AppHome {
  }

  interface AppProfile {
    'name': string;
  }

  interface AppRoot {
  }

  interface CosmoPatientForm {
    'patient': Patient;
  }

  interface CosmoPatientList {
    'patients': Patient[];
  }

  interface CosmoPatientListContainer {
  }
}

declare global {


  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
  }

  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new(): HTMLAppHomeElement;
  };

  interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
  }

  var HTMLAppProfileElement: {
    prototype: HTMLAppProfileElement;
    new(): HTMLAppProfileElement;
  };

  interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
  }

  var HTMLAppRootElement: {
    prototype: HTMLAppRootElement;
    new(): HTMLAppRootElement;
  };

  interface HTMLCosmoPatientFormElement extends Components.CosmoPatientForm, HTMLStencilElement {
  }

  var HTMLCosmoPatientFormElement: {
    prototype: HTMLCosmoPatientFormElement;
    new(): HTMLCosmoPatientFormElement;
  };

  interface HTMLCosmoPatientListElement extends Components.CosmoPatientList, HTMLStencilElement {
  }

  var HTMLCosmoPatientListElement: {
    prototype: HTMLCosmoPatientListElement;
    new(): HTMLCosmoPatientListElement;
  };

  interface HTMLCosmoPatientListContainerElement extends Components.CosmoPatientListContainer, HTMLStencilElement {
  }

  var HTMLCosmoPatientListContainerElement: {
    prototype: HTMLCosmoPatientListContainerElement;
    new(): HTMLCosmoPatientListContainerElement;
  };

  interface HTMLElementTagNameMap {
    'app-home': HTMLAppHomeElement;
    'app-profile': HTMLAppProfileElement;
    'app-root': HTMLAppRootElement;
    'cosmo-patient-form': HTMLCosmoPatientFormElement;
    'cosmo-patient-list': HTMLCosmoPatientListElement;
    'cosmo-patient-list-container': HTMLCosmoPatientListContainerElement;
  }
}

declare namespace LocalJSX {
  interface AppHome {
  }

  interface AppProfile {
    'name'?: string;
  }

  interface AppRoot {
  }

  interface CosmoPatientForm {
    'onPatientCreated'?: (event: CustomEvent<any>) => void;
    'onPatientUpdated'?: (event: CustomEvent<any>) => void;
    'patient'?: Patient;
  }

  interface CosmoPatientList {
    'onPatientSelected'?: (event: CustomEvent<any>) => void;
    'onPatientSelectedForDeletion'?: (event: CustomEvent<any>) => void;
    'onPatientSelectedForEdit'?: (event: CustomEvent<any>) => void;
    'patients'?: Patient[];
  }

  interface CosmoPatientListContainer {
  }

  interface IntrinsicElements {
    'app-home': AppHome;
    'app-profile': AppProfile;
    'app-root': AppRoot;
    'cosmo-patient-form': CosmoPatientForm;
    'cosmo-patient-list': CosmoPatientList;
    'cosmo-patient-list-container': CosmoPatientListContainer;
  }
}

export {LocalJSX as JSX};


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'app-home': LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
      'app-profile': LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
      'app-root': LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
      'cosmo-patient-form': LocalJSX.CosmoPatientForm & JSXBase.HTMLAttributes<HTMLCosmoPatientFormElement>;
      'cosmo-patient-list': LocalJSX.CosmoPatientList & JSXBase.HTMLAttributes<HTMLCosmoPatientListElement>;
      'cosmo-patient-list-container': LocalJSX.CosmoPatientListContainer & JSXBase.HTMLAttributes<HTMLCosmoPatientListContainerElement>;
    }
  }
}


